replicaCount: 1

nameOverride: ""
fullnameOverride: ""

application:
  image:
    repository: public.ecr.aws/l6z6v3j6/digital-land-platform
    pullPolicy: Always
    tag: staging
  environment:
    - name: S3_HOISTED_BUCKET
      value: https://digital-land-production-collection-dataset-hoisted.s3.eu-west-2.amazonaws.com
    - name: S3_COLLECTION_BUCKET
      value: https://digital-land-production-collection-dataset.s3.eu-west-2.amazonaws.com
    - name: WRITE_DATABASE_URL
      value: postgresql://postgres:postgres@localhost/postgres
    - name: READ_DATABASE_URL
      value: postgresql://postgres:postgres@localhost/postgres
    - name: ENVIRONMENT
      value: production
    - name: DATASETTE_URL
      value: https://datasette.digital-land.info
    - name: PORT
      value: '80'

companionContainers:
  - name: digital-land-db
    image: postgis/postgis:latest
    imagePullPolicy: IfNotPresent
    env:
      - name: POSTGRES_PASSWORD
        value: postgres
      - name: POSTGRES_USER
        value: postgres
    ports:
      - containerPort: 5432
    livenessProbe:
      exec:
        command: ["bash", "-c", "pg_isready -U $POSTGRES_USER"]
    readinessProbe:
      exec:
        command: ["bash", "-c", "pg_isready -U $POSTGRES_USER"]

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: digital-land.test
      paths:
        - path: /
          pathType: ImplementationSpecific
